### PR TITLE
Remove undocumented panic in with_native_roots

### LINKED ISSUE #187: panics "no CA certificates found"
Hi,

I have a project which have indirect dependency to `hyper-rustls`. During runtime, the binary panics:
```
thread '<unnamed>' panicked at 'no CA certificates found', /home/pierre/.cargo/registry/src/github.com-1ecc6299db9ec82
3/hyper-rustls-0.22.1/src/connector.rs:45:13
```

The version is `0.22.1`.
Note that the crash happens on Android device.

### PR DESCRIPTION
**Pull request by kayabaNerve**
Breaking API change as required to implement this safety.

Somewhat resolves #187.

### CODE REVIEW

File: examples/client.rs [hunk 1]
```diff
@@ -61,6 +61,7 @@ async fn run_client() -> io::Result<()> {
         None => rustls::ClientConfig::builder()
             .with_safe_defaults()
             .with_native_roots()
+            .expect("no CAs were present on the system")
```
Comment (cpu) [inline examples/client.rs:64]:
```suggestion
            .expect("no native root CAs were present on the system")
```

File: src/config.rs [hunk 2]
```diff
@@ -10,7 +10,9 @@ pub trait ConfigBuilderExt {
     /// rustls-native-certs
     #[cfg(feature = "rustls-native-certs")]
     #[cfg_attr(docsrs, doc(cfg(feature = "rustls-native-certs")))]
-    fn with_native_roots(self) -> ConfigBuilder<ClientConfig, WantsTransparencyPolicyOrClientCert>;
+    fn with_native_roots(
```
Comment (cpu) [inline src/config.rs:13]: I think the rustdoc comment for this trait fn should mention why it might return `None`, and to suggest using `with_webpki_roots` in that circumstance.

File: src/config.rs [hunk 3]
```diff
@@ -45,9 +49,12 @@ impl ConfigBuilderExt for ConfigBuilder<ClientConfig, WantsVerifier> {
             valid_count,
             invalid_count
         );
-        assert!(!roots.is_empty(), "no CA certificates found");
+        if roots.is_empty() {
+            crate::log::debug!("no CA certificates found");
```
Comment (cpu) [inline src/config.rs:53]:
```suggestion
            crate::log::debug!("no native root CA certificates found");
```

File: src/lib.rs [hunk 4]
```diff
@@ -14,6 +14,7 @@
 //! let url = ("https://hyper.rs").parse().unwrap();
 //! let https = hyper_rustls::HttpsConnectorBuilder::new()
 //!     .with_native_roots()
+//!     .expect("no CAs were present on the system")
```
Comment (cpu) [inline src/lib.rs:17]:
```suggestion
//!     .expect("no native root CAs were present on the system")
```

File: src/lib.rs [hunk 5]
```diff
@@ -59,6 +60,7 @@
 //! let key = rustls::PrivateKey(keys[0].clone());
 //! let https = hyper_rustls::HttpsConnectorBuilder::new()
 //!     .with_native_roots()
+//!     .expect("no CAs were present on the system")
```
Comment (cpu) [inline src/lib.rs:63]:
```suggestion
//!     .expect("no native root CAs were present on the system")
```

**Review by cpu — COMMENTED** [review]
Hi, thanks for the PR. I have a few initial comments.

At a meta-level I'm also wondering whether we should augment this API surface with something feature-gated on webpki-roots that allows trying to find native trust anchors, but automatically falling back to bundled webpki-roots trust anchors when it comes up empty. I suspect that might be more user friendly, and matches the approach offered in rustls-platform-verifier (see some discussion in https://github.com/rustls/rustls-platform-verifier/issues/12).

The rustls-platform-verifier work was motivated by observation in the field that `openssl-probe` wasn't always reliable, and that's the dependency underpinning rustls-native-roots on non-MacOS unix systems. What platform you're seeing this panic on? There were similar requests for more information in #187 that nobody has provided to date.

**Comment by kayabaNerve** [comment]
> but automatically falling back to bundled webpki-roots trust anchors when it comes up empty. I suspect that might be more user friendly, and matches the approach offered in rustls-platform-verifier (see some discussion in [rustls/rustls-platform-verifier#12](https://github.com/rustls/rustls-platform-verifier/issues/12)).

While I'd support this, I believe that should be an additional, recommended function. Not the replacement behavior for this function.

I observed this on a Linux system without ca-certificates installed. Specifically, a GH CI runner I uninstalled most packages from. Then, I also encountered it on a Debian slim Docker image.

I'm fine updating the documentation :+1:

**Comment by kayabaNerve** [comment]
Done

File: src/config.rs [hunk 6]
```diff
@@ -23,7 +28,9 @@ impl ConfigBuilderExt for ConfigBuilder<ClientConfig, WantsVerifier> {
     #[cfg(feature = "rustls-native-certs")]
     #[cfg_attr(docsrs, doc(cfg(feature = "rustls-native-certs")))]
     #[cfg_attr(not(feature = "logging"), allow(unused_variables))]
-    fn with_native_roots(self) -> ConfigBuilder<ClientConfig, WantsTransparencyPolicyOrClientCert> {
+    fn with_native_roots(
+        self,
+    ) -> Option<ConfigBuilder<ClientConfig, WantsTransparencyPolicyOrClientCert>> {
```
Comment (ctz) [inline src/config.rs:33]: my feeling is that this should be returning a `Result` with a `Box<dyn std::error::Error>` or `std::io::Error`

then the `.expect("could not load platform certs")` line below can become `?` to avoid a reachable panic there.

File: src/config.rs [hunk 7]
```diff
@@ -45,9 +52,12 @@ impl ConfigBuilderExt for ConfigBuilder<ClientConfig, WantsVerifier> {
             valid_count,
             invalid_count
         );
-        assert!(!roots.is_empty(), "no CA certificates found");
+        if roots.is_empty() {
+            crate::log::debug!("no native root CA certificates found");
+            None?
```
Comment (ctz) [inline src/config.rs:57]: and this can return something more useful, -- i suggest including the logged message, and the `valid_count` and `invalid_count` diagnostics too (i appreciate there's logging going on, but it's less immediate than returning the same stuff in a `Result::Err`, even if it gets smushed into a String along the way)

File: src/connector/builder.rs [hunk 8]
```diff
@@ -59,12 +59,14 @@ impl ConnectorBuilder<WantsTlsConfig> {
     /// [with_safe_defaults]: rustls::ConfigBuilder::with_safe_defaults
     #[cfg(feature = "rustls-native-certs")]
     #[cfg_attr(docsrs, doc(cfg(feature = "rustls-native-certs")))]
-    pub fn with_native_roots(self) -> ConnectorBuilder<WantsSchemes> {
-        self.with_tls_config(
-            ClientConfig::builder()
-                .with_safe_defaults()
-                .with_native_roots()
-                .with_no_client_auth(),
+    pub fn with_native_roots(self) -> Option<ConnectorBuilder<WantsSchemes>> {
```
Comment (ctz) [inline src/connector/builder.rs:62]: ditto, `Result`

**Comment by djc** [comment]
Usually we would postpone builder API errors until the end of the builder chain, which this would subvert.

**Comment by kayabaNerve** [comment]
While I'm not against standing in the way in convention with PR, I'd note that policy makes it more difficult to identify which step in the process failed as you get one Result for all steps, not one Result for each step which may fail. While the error itself may reasonably allowing discovery of the issue, the proposed path here is if `with_native_roots` returns None/error, callers fallback to `with_webpki_roots`. They'd need a way to introspect the final Result to check if it's due to this specific issue in order to safely execute the suggested fallback (unless they simply blindly try again with `with_webpki_roots`).

Since the suggested error to replace this with was `std:io::Error`, not `hyper_rustls::config::BuildError`, this seems infeasible.

Also, while I do agree the error would be more descriptive, I think None to signify there were no valid roots on the system is fine. Regardless, I'm happy to move it to an error, so long as the policy on *where to put the error* and the suggested mediation path is resolved.

**Comment by kayabaNerve** [comment]
@ctz Resolved your comments :)

File: src/config.rs [hunk 9]
```diff
@@ -8,9 +8,14 @@ use rustls::{ClientConfig, ConfigBuilder, WantsVerifier};
 pub trait ConfigBuilderExt {
     /// This configures the platform's trusted certs, as implemented by
     /// rustls-native-certs
+    ///
+    /// This will return None if no valid certs were found. In that case,
```
Comment (cpu) [inline src/config.rs:12]: I think this comment fell out-of-date with the impl after the change to use `Result`.

Comment (kayabaNerve) [reply src/config.rs]: It did, sorry. Fixed!

**Comment by kayabaNerve** [comment]
Also, the lib.rs example is failing as its function doesn't return an error, so that does have to be an expect...

**Review by cpu — APPROVED** [review]
Thank you.

I will circle back with the idea of making a new combined "try native then webpki-roots" method later on (unless you want to tackle that in a follow-up yourself).

**Comment by kayabaNerve** [comment]
*Personally*, I think that's trivial enough it doesn't have to be in hyper-rustls, but it's hard to argue against libs adding extra helpers to go the extra mile in friendliness...

**Comment by kayabaNerve** [comment]
Anything else needed for this to be merged?

**Comment by cpu** [comment]
> Anything else needed for this to be merged?

Looks like there's a CI failure from another examples in `lib.rs` that need to `expect`. Could you fix that up @kayabaNerve? It would also be helpful if you could squash your commit history.

**Comment by kayabaNerve** [comment]
Oh, sorry. I have no idea how I missed that. Will correct that now.

Would love to get this included with whatever release updates to 1.0 :)

**Comment by kayabaNerve** [comment]
Pushed a new single commit.

**Comment by kayabaNerve** [comment]
CI passed :D

**Review by ctz — APPROVED** [review]
this looks good to me

**Review by cpu — APPROVED** [review]

**Review by djc — APPROVED** [review]

**Comment by cpu** [comment]
Thanks kayabaNerve.

**Comment by kayabaNerve** [comment]
Happy to.
